New clientcount download
abtassociates/eva pull request #143
Opened 2022-12-29 22:51 UTC by alex-silverman

2023-01-14 15:05 UTC, kiadso requested changes
These numbers are looking good. In the card, I added a spot for the 3rd tab that outlines which columns are needed there. I'm going to list a few small things that need attention before merge:

- [ ]  For each tab, column order to align with the way the card has it
- [ ]  The Date Range tab is missing the Exit-related columns
- [ ]  Added some arrange() code to the card 

I really like the workbook with the 3 tabs in it. I know we talked about where to put the button since the "Select Project" doesn't affect its results. The date range does affect the results. So I'm wondering if we move the Select Project to its own box named Project-level or something and put it below the box that already exists? We can make it that same color as the other project-level boxes..

2023-01-15 16:26 UTC, alex-silverman commented on 01_cohorts.R
> +    LengthOfStay
i think we decided to remove this variable. I'm not sure why you were seeing it. My github shows maybe you were looking at an outdated version?

2023-01-15 16:34 UTC, alex-silverman commented
> These numbers are looking good. In the card, I added a spot for the 3rd tab that outlines which columns are needed there. I'm going to list a few small things that need attention before merge:
> 
> * [ ]   For each tab, column order to align with the way the card has it
> * [ ]   The Date Range tab is missing the Exit-related columns
> * [ ]   Added some arrange() code to the card
> 
> I really like the workbook with the 3 tabs in it. I know we talked about where to put the button since the "Select Project" doesn't affect its results. The date range does affect the results. So I'm wondering if we move the Select Project to its own box named Project-level or something and put it below the box that already exists? We can make it that same color as the other project-level boxes..



> These numbers are looking good. In the card, I added a spot for the 3rd tab that outlines which columns are needed there. I'm going to list a few small things that need attention before merge:
> 
> * [ ]   For each tab, column order to align with the way the card has it
> * [ ]   The Date Range tab is missing the Exit-related columns
> * [ ]   Added some arrange() code to the card
> 
> I really like the workbook with the 3 tabs in it. I know we talked about where to put the button since the "Select Project" doesn't affect its results. The date range does affect the results. So I'm wondering if we move the Select Project to its own box named Project-level or something and put it below the box that already exists? We can make it that same color as the other project-level boxes..

1/15/23 AS: I'm not seeing the 3rd tab in the card. But, for consistency, shouldn't the 3rd tab - the details tab - just include the same columns as the Details table in the app?

2023-02-07 19:58 UTC, alex-silverman commented
I think this is just waiting on your approval now, @kiadso!

2023-02-07 20:34 UTC, merged