407 zero utilization warnings for dv programs in evas dq reports
abtassociates/eva pull request #420
Opened 2023-11-07 13:47 UTC by kiadso

Fixes issue #407 and also adds a new issue called "VSP participating in HMIS"

2023-11-07 21:24 UTC, kiadso commented on public-resources/EvaChecks.csv
> +dq,Warning,Incomplete or Don't Know/Refused Name,3.01.5 - Name: Name Data Quality,"This record is being flagged because it is incomplete. Some clients may decline or be unable to provide the answer t
we want to prevent these edits

2023-11-07 21:44 UTC, kiadso commented on sandbox/change-sample-data/test-vsp-hmis-participating.R
> +  base::intersect(vsp_projects, participating_projects)
this code^ is all repeat from the pdde_checker.R and is here for convenience only. the real value in this script is below (what we expect)

2023-11-08 14:21 UTC, alex-silverman requested changes
just need a changelog

2023-11-09 15:08 UTC, alex-silverman approved these changes

2023-11-09 15:13 UTC, merged