Populate plot selections
abtassociates/eva pull request #538
Opened 2024-08-07 21:06 UTC by kiadso

this fixes the plot header that displays what has been selected. Only some of them were working before.

2024-08-09 19:32 UTC, alex-silverman commented on 07a_system_activity_plots.R
> +    getNameByValue(syso_spec_pops_people, input$syso_spec_pops),
It looks like syso_spec_pops_cats() used to dynamically call syso_spec_pops_people or syso_spec_pops_hoh, depending on methodology type. But syso_spec_pops_hoh doesn't seem to be a thing. So I would just delete the commented out line here and the syso_spec_pops_cats() reactive in the server.R file.

2024-08-09 20:02 UTC, alex-silverman requested changes
Mostly small suggestions for removing no-longer-necessary comments. Two small, not-that important changes to make the detection and labelling of "all ages" or "all genders" more dynamic. One likely important change to pass `input$methodology_type` to `syso_gender_cats()`

2024-08-12 14:33 UTC, kiadso commented on 07a_system_activity_plots.R
> +    if_else(length(input$syso_gender) == 5,
I used your second suggestion- thanks! :)

2024-08-12 14:34 UTC, kiadso commented on 07a_system_activity_plots.R
> +            getNameByValue(syso_gender_cats(), input$syso_gender)),
YEP this was causing problems, tahnks!

2024-08-12 18:32 UTC, alex-silverman requested changes
A few small changes, which I can make

2024-08-12 18:32 UTC, alex-silverman commented on 07a_system_activity_plots.R
> +    if (length(input$syso_age) != 11)
let's make this more dynamic, in case the number of age categories change.

2024-08-12 18:32 UTC, alex-silverman commented on 07a_system_activity_plots.R
>    list(
Can we clean up this whole block? It's a little hard to see what's going on. Something like this?

```
  detail_line <- function(detail_label, val_list, inputVal) {
    return(
      HTML(glue(
        "<b>{detail_label}:</b> {getNameByValue(val_list, inputVal)} <br>"
      ))
    )
  }
  list(
    strong("Date Range: "),
    
    ReportStart(), " to ", ReportEnd(), br(),
    
    if (getNameByValue(syso_hh_types, input$syso_hh_type) != "All People")
      detail_line("Household Type", syso_hh_types, input$syso_hh_type),
    
    detail_line("Level of Detail", syso_level_of_detail, input$syso_level_of_detail),
    
    if (getNameByValue(syso_project_types, input$syso_project_type) != "All")
      detail_line("Project Type", syso_project_types, input$syso_project_type),
    
    detail_line("Methodology Type", syso_methodology_types, input$methodology_type),

    if (length(input$syso_age) != length(syso_age_cats))
      HTML(glue(
        "<b>Age:</b> {paste(input$syso_age, collapse = ', ')} <br>"
      )),
    
    if (length(input$syso_gender) != length(syso_gender_cats(input$methodology_type)))
      detail_line("Gender", syso_gender_cats(input$methodology_type), input$syso_gender),
    
    if (getNameByValue(syso_race_ethnicity_cats(input$methodology_type),
                       input$syso_race_ethnicity) != "All Races/Ethnicities")
      strong("Race/Ethnicity: "), str_sub(
        getNameByValue(
          unlist(syso_race_ethnicity_cats(input$methodology_type)),
          input$syso_race_ethnicity
        ),
        start = str_locate(getNameByValue(
          unlist(syso_race_ethnicity_cats(input$methodology_type)),
          input$syso_race_ethnicity
        ), "\\.")[, 1] + 1,
        end = -1L
      ), br(),
    if(getNameByValue(syso_spec_pops_people, input$syso_spec_pops) != "None")
      detail_line("Special Populations", syso_spec_pops_people, input$syso_spec_pops)
```

2024-08-12 18:32 UTC, alex-silverman commented on 07a_system_activity_plots.R
> +                               input$syso_race_ethnicity) != "All")
I think this should be "All Races/Ethnicities"

2024-08-12 18:56 UTC, alex-silverman commented
Also, is this an issue we need to deal with?

![image](https://github.com/user-attachments/assets/45294677-9d89-453b-9e0e-3da33d53acf4)

2024-08-12 19:02 UTC, alex-silverman commented
@kiadso - i made the suggested changes. Feel free to revert back to the previous commit, or go ahead and merge! I'll approve now

2024-08-12 19:02 UTC, alex-silverman approved these changes

2024-08-13 13:30 UTC, merged