Metadata updates
abtassociates/eva pull request #662
Opened 2024-12-11 22:37 UTC by zabalad

Added system overview info, chart revisions, updated color palette
https://github.com/orgs/abtassociates/projects/1/views/1?pane=issue&itemId=84422117

2025-02-13 13:30 UTC, kiadso approved these changes
Hi, thank you for your patience- looks great!

2025-02-18 15:37 UTC, alex-silverman commented on metadata-analysis/Metadata-Analysis.Rmd
> +
seems like the hits actually started increasing in August, especially around NHSDC. Where are you seeing decreases?

![image](https://github.com/user-attachments/assets/3d324f61-5774-4170-ba3b-25ddb3c7e16a)

2025-02-18 20:08 UTC, alex-silverman requested changes
Some small changes, mostly around combining filters, especially with more intuitive filters that align with what we're trying to capture, but one bigger one:

Given https://github.com/abtassociates/eva/pull/718, it may be worth looking into fixing previous weeks/months data that are overcounting Tabular Data downloads. I.e., every time we log a PPT download, we ALSO log a tabular download. So we should remove a tabular download from the metadata for every PPT download prior to whenever we merge that PR.

2025-02-24 18:58 UTC, zabalad commented on metadata-analysis/Metadata-Analysis.Rmd
> +  filter(!(Event %in% c('User on tabHome'))) %>%
Edit made

2025-02-24 19:01 UTC, zabalad commented on metadata-analysis/Metadata-Analysis.Rmd
> +#
I'm ok to remove, this but will bring up with team just in case

2025-02-24 19:03 UTC, zabalad commented on metadata-analysis/Metadata-Analysis.Rmd
> +  filter(!str_detect(Event, "Successful upload")) %>%
Edit made

2025-02-24 19:04 UTC, zabalad commented on metadata-analysis/Metadata-Analysis.Rmd
Added

2025-02-24 21:53 UTC, zabalad commented on metadata-analysis/Metadata-Analysis.Rmd
> +  filter(str_detect(Event, "System Overview")) %>%
Combined 1st and 3rd filters

2025-02-24 22:14 UTC, zabalad commented on metadata-analysis/Metadata-Analysis.Rmd
> +  mutate(Event2 = case_when((!str_detect(Event, "System Overview")) ~ "DQ download",
Yes, but that's OK because we want it to

2025-02-25 19:58 UTC, zabalad commented on metadata-analysis/Metadata-Analysis.Rmd
> +  filter(str_detect(Event, "System Overview")) %>%
1st and 3rd filters combined

2025-02-25 20:07 UTC, alex-silverman commented on server.R
> +      logMetadata(paste0("Unpacked file size, all files (KB) = ", sum(zipContents$Length) / 1024))
Let's add a "DEVOPS - " prefix to these new logMetadata calls so they can easily be ignored in the rest of the metadata analysis

2025-02-25 20:18 UTC, zabalad commented
> Some small changes, mostly around combining filters, especially with more intuitive filters that align with what we're trying to capture, but one bigger one:
> 
> Given #718, it may be worth looking into fixing previous weeks/months data that are overcounting Tabular Data downloads. I.e., every time we log a PPT download, we ALSO log a tabular download. So we should remove a tabular download from the metadata for every PPT download prior to whenever we merge that PR.

Good catch, will need to reduce tabular downloads by # of ppt downloads for each type of download

2025-02-25 20:19 UTC, zabalad commented on metadata-analysis/Metadata-Analysis.Rmd
> +  filter(!str_detect(Event, "Sys Inflow Outflow")) %>%
Good catch - need to fix

2025-02-25 20:23 UTC, zabalad commented on metadata-analysis/Metadata-Analysis.Rmd
> +  filter(!str_detect(Event, "Sys Inflow Outflow")) %>%
> is this supposed to include DQ AND PDDE?

Yes!

2025-02-25 20:27 UTC, alex-silverman commented on metadata-analysis/Metadata-Analysis.Rmd
> +  filter(!str_detect(Event, "Sys Inflow Outflow")) %>%
actually, after revisitng with you, this is correct as-is. I originally was thinking it should be more affirmative, but you're cpaturing not just DQ and PDDE, but also Client counts and FSA. So easier/better to just take all downloads MINUS System Overview + Sys Inflow Outflow.

2025-02-25 22:33 UTC, zabalad commented on server.R
> +      logMetadata(paste0("Unpacked file size, all files (KB) = ", sum(zipContents$Length) / 1024))
Done

2025-03-03 22:26 UTC, zabalad commented
> > Some small changes, mostly around combining filters, especially with more intuitive filters that align with what we're trying to capture, but one bigger one:
> > Given #718, it may be worth looking into fixing previous weeks/months data that are overcounting Tabular Data downloads. I.e., every time we log a PPT download, we ALSO log a tabular download. So we should remove a tabular download from the metadata for every PPT download prior to whenever we merge that PR.
> 
> Good catch, will need to reduce tabular downloads by # of ppt downloads for each type of download - add code to modify the log before showing any graphs

Done

2025-06-09 12:55 UTC, merged